"""add workflow configurations

Revision ID: 1d8c914d5c5d
Revises: 43b15d420624
Create Date: 2026-09-17 20:10:15.611108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d8c914d5c5d'
down_revision: Union[str, Sequence[str], None] = '43b15d420624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('workflow_name', sa.String(length=150), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_type', sa.Enum('MANUAL', 'DAILY', name='workflow_schedule_type'), nullable=False),
    sa.Column('schedule_hour', sa.Integer(), nullable=True),
    sa.Column('schedule_minute', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_configurations_clinic_id'), 'workflow_configurations', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_workflow_configurations_workflow_name'), 'workflow_configurations', ['workflow_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_configurations_workflow_name'), table_name='workflow_configurations')
    op.drop_index(op.f('ix_workflow_configurations_clinic_id'), table_name='workflow_configurations')
    op.drop_table('workflow_configurations')
    # ### end Alembic commands ###
