"""add workflow configuration uniqueness

Revision ID: 7db1091b21e8
Revises: 27af5cbf5eab
Create Date: 2026-09-18 01:52:32.659031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7db1091b21e8'
down_revision: Union[str, Sequence[str], None] = '27af5cbf5eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_workflow_configurations_clinic_workflow', 'workflow_configurations', ['clinic_id', 'workflow_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_workflow_configurations_clinic_workflow', 'workflow_configurations', type_='unique')
    # ### end Alembic commands ###
