from datetime import datetime, timedelta, timezone
from typing import Any
from uuid import uuid4

import bcrypt
from jose import JWTError, jwt

from backend.app.core.config import settings


# ==========================================================
# PASSWORD SECURITY
# ==========================================================


def hash_password(password: str) -> str:
    """
    Convert a plain-text password into a secure bcrypt hash.

    bcrypt supports passwords up to 72 bytes. The API schemas
    already enforce a maximum password length of 72 characters.
    """

    password_bytes = password.encode("utf-8")

    if len(password_bytes) > 72:
        raise ValueError(
            "Password cannot exceed 72 bytes"
        )

    hashed_password = bcrypt.hashpw(
        password_bytes,
        bcrypt.gensalt(),
    )

    return hashed_password.decode("utf-8")


def verify_password(
    plain_password: str,
    hashed_password: str,
) -> bool:
    """
    Check whether a plain-text password matches
    its stored bcrypt hash.

    Invalid hashes or invalid input return False rather
    than exposing internal bcrypt errors.
    """

    password_bytes = plain_password.encode("utf-8")
    hashed_password_bytes = hashed_password.encode("utf-8")

    if len(password_bytes) > 72:
        return False

    try:
        return bcrypt.checkpw(
            password_bytes,
            hashed_password_bytes,
        )
    except (ValueError, TypeError):
        return False


# ==========================================================
# JWT SECURITY
# ==========================================================


ACCESS_TOKEN_TYPE = "access"


def create_access_token(
    data: dict[str, Any],
) -> str:
    """
    Create a signed JWT access token.

    Security claims added automatically:

    - sub: user identifier
    - iat: issued-at timestamp
    - exp: expiration timestamp
    - jti: unique token identifier
    - typ: access token type

    Security-sensitive claims are generated by this function
    and cannot be overridden through the input dictionary.
    """

    to_encode = data.copy()

    # The subject is required for identifying the authenticated
    # user.
    subject = to_encode.get("sub")

    if not subject:
        raise ValueError(
            "JWT subject (sub) is required"
        )

    if not isinstance(subject, str):
        raise ValueError(
            "JWT subject (sub) must be a string"
        )

    now = datetime.now(timezone.utc)

    expire = now + timedelta(
        minutes=settings.jwt_access_token_expire_minutes
    )

    # Always generate security-sensitive claims here.
    #
    # This prevents callers from supplying their own exp,
    # iat, jti, or token type.
    to_encode.update(
        {
            "iat": now,
            "exp": expire,
            "jti": str(uuid4()),
            "typ": ACCESS_TOKEN_TYPE,
        }
    )

    return jwt.encode(
        to_encode,
        settings.jwt_secret_key,
        algorithm=settings.jwt_algorithm,
    )


def decode_access_token(
    token: str,
) -> dict[str, Any]:
    """
    Decode and validate a JWT access token.

    Validation includes:

    - Token is not empty
    - Signature verification
    - Algorithm verification
    - Expiration verification
    - Issued-at verification
    - Required subject claim
    - Required expiration claim
    - Required issued-at claim
    - Required JWT ID
    - Required access-token type
    """

    if not token or not token.strip():
        raise ValueError(
            "Invalid or expired access token"
        )

    try:
        payload = jwt.decode(
            token,
            settings.jwt_secret_key,
            algorithms=[settings.jwt_algorithm],
            options={
                "verify_signature": True,
                "verify_exp": True,
                "verify_iat": True,
                "require_sub": True,
                "require_exp": True,
                "require_iat": True,
                "require_jti": True,
                "require_typ": True,
            },
        )

        # --------------------------------------------------
        # SUBJECT
        # --------------------------------------------------

        subject = payload.get("sub")

        if not subject or not isinstance(subject, str):
            raise ValueError(
                "Invalid access token subject"
            )

        # --------------------------------------------------
        # TOKEN ID
        # --------------------------------------------------

        token_id = payload.get("jti")

        if not token_id or not isinstance(token_id, str):
            raise ValueError(
                "Invalid access token identifier"
            )

        # --------------------------------------------------
        # TOKEN TYPE
        # --------------------------------------------------

        token_type = payload.get("typ")

        if token_type != ACCESS_TOKEN_TYPE:
            raise ValueError(
                "Invalid access token type"
            )

        return payload

    except (JWTError, ValueError, TypeError) as exc:
        raise ValueError(
            "Invalid or expired access token"
        ) from exc